services:
  app:
    build:
      context: .
      target: dev
    container_name: cms_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - cms_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: host.docker.internal
      REDIS_HOST: redis

  web:
    image: nginx:alpine
    container_name: cms_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cms_network

  redis:
    image: redis:alpine
    container_name: cms_redis
    restart: unless-stopped
    networks:
      - cms_network

networks:
  cms_network:
    driver: bridge
